In [3]:
import numpy as np

In [6]:
a=(1,2,5,5)

In [12]:
b=np.array(a)
b

array([1, 2, 5, 5])

In [13]:
type(b)

numpy.ndarray

In [15]:
np.ndim(b)

1

In [18]:
c=np.array([b])
c

array([[1, 2, 5, 5]])

In [19]:
np.ndim(c)

2

In [22]:
c=[[[1,2,3,4],[5,4,5,2],[2,4,5,4]]]

In [23]:
np.ndim(c)

3

# placeholder

In [29]:
p=np.ones([4,3,4])
p

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
np.ndim(p)

3

In [33]:
np.zeros((2,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [38]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [39]:
np.full((2,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [42]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [48]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [51]:
np.random.random(10)floate

array([0.45069319, 0.04658081, 0.3550426 , 0.26280647, 0.10748185,
       0.57518666, 0.95275044, 0.91850236, 0.77618553, 0.65022388])

In [66]:
np.random.randint(2,100) #integer value from 

45

In [71]:
b=np.arange(1,13).reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
c=[b<5]
c

[array([[ True,  True,  True],
        [ True, False, False],
        [False, False, False],
        [False, False, False]])]

In [77]:
d=b.transpose()
d

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [89]:
arr=np.add(d,5)
arr

array([[ 6,  9, 12, 15],
       [ 7, 10, 13, 16],
       [ 8, 11, 14, 17]])

In [96]:
arr[arr<13]

array([ 6,  9, 12,  7, 10,  8, 11])

In [81]:
np.subtract(d,6)

array([[-5, -2,  1,  4],
       [-4, -1,  2,  5],
       [-3,  0,  3,  6]])

In [84]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
np.size(d)

12

In [87]:
np.random.randint(500,size=(3,4))

array([[210, 147, 365, 457],
       [248, 448, 472, 255],
       [293,   0, 497, 194]])