In [1]:
import numpy as np

In [2]:
my_list=[1,5,6,8,5,5,2,5]

In [4]:
#one diamenstion array
arr=np.array(my_list)  # we convert list to array
arr   

array([1, 5, 6, 8, 5, 5, 2, 5])

In [6]:
type(arr)       #we see that array

numpy.ndarray

In [7]:
arr.shape

(8,)

In [7]:
#multidiamenstion array
my_list1=[1,2,5,6,4]
my_list2=[1,3,7,6,11]
my_list3=[1,9,5,10,9]


In [10]:
arr1=np.array([my_list1,my_list2,my_list3])
arr1

array([[ 1,  2,  5,  6,  4],
       [ 1,  3,  7,  6, 11],
       [ 1,  9,  5, 10,  9]])

In [25]:
arr1.shape

(3, 5)

In [11]:
arr1.reshape(5,3)   # mae sure our values is always 5*3=15

array([[ 1,  2,  5],
       [ 6,  4,  1],
       [ 3,  7,  6],
       [11,  1,  9],
       [ 5, 10,  9]])

# indexing

In [4]:
arr=np.array([1,2,5,2,5,2,1,5,5])

In [16]:
arr[5]

2

In [17]:
arr[2:5]

array([5, 2, 5])

In [ ]:
#indexing on two diamentioal 

In [12]:
arr1

array([[ 1,  2,  5,  6,  4],
       [ 1,  3,  7,  6, 11],
       [ 1,  9,  5, 10,  9]])

In [13]:
#arr1[1:6 for row,
#2:5 for column]
arr1[1:6,2:5]
                                                                                        

array([[ 7,  6, 11],
       [ 5, 10,  9]])

In [15]:
arr1[0:2,1:3]

array([[2, 5],
       [3, 7]])

In [32]:
arr1[:,:]

array([[ 1,  2,  5,  6,  4],
       [ 1,  3,  7,  6, 11],
       [ 1,  9,  5, 10,  9]])

In [36]:
arr1[2,4]

9

In [37]:
arr1[1,2]

7

In [40]:
arr1[1:3,2:4]

array([[ 7,  6],
       [ 5, 10]])

In [41]:
arr1[1:3,3:5]

array([[ 6, 11],
       [10,  9]])

In [43]:
arr2=np.arange(0,10,2)
arr2

array([0, 2, 4, 6, 8])

In [48]:
arr3=np.linspace(2,10,10) [#2-10 equally 10 values]
arr3

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [51]:
arr2[2]=20
arr2

array([ 0,  2, 20,  6,  8])

In [53]:
#brodcasting 
arr2[2:]=45
arr2

array([ 0,  2, 45, 45, 45])

In [54]:
#first take copy of prviouse
arr3=arr2.copy()
arr2[3:]=1000
arr2

array([   0,    2,   45, 1000, 1000])

In [58]:
#you can check my priviouse array
arr3

array([ 0,  2, 45, 45, 45])

In [67]:
#check the array 
arr5=np.array([0,0,2,54,5,52,5])

In [68]:
arr5>2

array([False, False, False,  True,  True,  True,  True])

In [71]:
#array manupulation
print(arr5*5)
print(arr5/5)
print(arr5+5)

[  0   0  10 270  25 260  25]
[ 0.   0.   0.4 10.8  1.  10.4  1. ]
[ 5  5  7 59 10 57 10]


In [72]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
np.arange(0,12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [87]:
arr

array([1, 2, 5, 2, 5, 2, 1, 5, 5])

In [88]:
#give me that array only less than 4
arr[arr<4] 

array([1, 2, 2, 2, 1])

In [107]:
a=np.ones([2,10],dtype=bool)
a

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [105]:
#array operation 
a*5+3-6

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [100]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [135]:
#it give uniform disrtibution ---all values equally likely
np.random.rand(3,5)

array([[0.33833166, 0.31627379, 0.60890168, 0.97108595, 0.28281994],
       [0.77166931, 0.76855285, 0.57077112, 0.87711951, 0.33010542],
       [0.3334704 , 0.77698238, 0.13753976, 0.99538253, 0.92492173]])

In [139]:
#it give the value standrad normal distribution
np.random.randn(4,5)

array([[ 1.08976474, -0.82407274, -0.21448296, -0.41890979, -0.29866643],
       [-0.83004642,  0.88138246,  0.58041155, -0.05253973,  2.1590629 ],
       [-0.73427349,  0.70454185,  1.1172116 , -0.26014716,  0.93935543],
       [ 0.03464089, -2.25661334, -1.06887537, -0.26836206,  0.30144959]])

In [164]:
#randint it give me 14 values betwen 2-25 and reshape it 7 row and 2 columns

np.random.randint(2,25,14).reshape(7,2)

array([[ 3, 21],
       [10, 16],
       [ 5, 18],
       [18,  4],
       [15, 21],
       [12, 20],
       [ 4, 22]])

In [166]:
#random sample
np.random.sample()

array([[0.38420922, 0.45926719, 0.1496577 , 0.30645011, 0.17425154],
       [0.06783785, 0.89450802, 0.15396006, 0.09366257, 0.94660265]])