In [1]:
import numpy as np

# crating array

In [2]:
a=np.array([1,2,3])

In [4]:
a.size

3

In [5]:
type(a)

numpy.ndarray

In [7]:
a.ndim

1

In [12]:
b=np.array([[1,2,3],[4,5,6]])

In [9]:
b.ndim

2

In [33]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
c.ndim

3

# initial placeholder

In [18]:
np.zeros((4,4,3))   #4-how many square,4-how many row,3-how many column

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.ones((4,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
np.arange(1,25,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [23]:
np.empty((3,4,5))

array([[[1.16561870e-311, 1.16559100e-311, 0.00000000e+000,
         0.00000000e+000, 0.00000000e+000],
        [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
         1.35717430e+131, 3.44357007e-086],
        [4.07356331e+223, 6.01347002e-154, 7.06743455e-096,
         1.81148490e-152, 8.94213159e+130],
        [1.05089651e-153, 6.12743486e-154, 6.14099335e-071,
         4.57667790e-072, 4.11083808e+223]],

       [[8.94213159e+130, 7.06743455e-096, 1.81148490e-152,
         8.94213159e+130, 1.05089651e-153],
        [6.12743486e-154, 6.14099335e-071, 4.57667790e-072,
         6.01391519e-154, 3.48987493e-086],
        [3.44357007e-086, 1.81154498e-152, 1.20336039e+132,
         1.05089651e-153, 6.12743486e-154],
        [6.14099335e-071, 4.57667790e-072, 6.01391519e-154,
         3.48987493e-086, 3.44357007e-086]],

       [[6.01347176e-154, 7.06764512e-096, 7.19081964e+140,
         6.12743633e-154, 6.19316963e-071],
        [4.57667790e-072, 6.01391519e-154, 3.48987493e-086,


In [3]:
np.full((3,2,2),7)    #2 row and 2 columns all values 7

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [30]:
np.eye(10)  # square matrix of 10*10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
np.linspace(1,10,5) # 1 to 10 give 5 values

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [8]:
np.random.random((4,3,2)) #create random matrix 3 and 2 columns

array([[[0.12411403, 0.52507041],
        [0.2593622 , 0.60903345],
        [0.93009061, 0.9900255 ]],

       [[0.1777431 , 0.43295207],
        [0.14609511, 0.02597208],
        [0.4366519 , 0.01141959]],

       [[0.09607237, 0.64189474],
        [0.55452546, 0.94048388],
        [0.62365258, 0.77562372]],

       [[0.75552942, 0.95735993],
        [0.77025996, 0.5502883 ],
        [0.0453608 , 0.42622675]]])

# method for sorting and seraching

In [36]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
d=np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
e=np.concatenate((d,b)) #concatnate same dimension for this
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [44]:
np.sort(e) #it give sorted matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [47]:
e.reshape((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 2.],
       [3., 4., 5., 6.]])

In [48]:
e.max(axis=0)  #1 ROW FROM THAT MATRIX

array([4., 5., 6.])

In [49]:
e.max(axis=1)  #1 COLUMN FROM THAT MATRIX

array([1., 1., 3., 6.])

In [52]:
e.transpose() #row to column and column to row 

array([[1., 1., 1., 4.],
       [1., 1., 2., 5.],
       [1., 1., 3., 6.]])

In [53]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [61]:
e.size #it give total element

12

In [63]:
e.ndim

2

In [64]:
e.dtype

dtype('float64')

In [68]:
np.random.randint(500,size=(3,4))   #take till 10 number and give me 3,4 matrix

array([[431, 284, 170, 220],
       [ 69, 360, 368, 166],
       [400, 135, 385,   7]])

In [70]:
e.astype(float)  #type casting

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [3., 4.],
       [5., 6.]])

# element wise opration

In [14]:
a

array([1, 2, 3])

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.add(a,b)

array([[2, 4, 6],
       [5, 7, 9]])

In [74]:
np.subtract(a,b)

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [75]:
np.divide(a,b)

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [76]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [81]:
np.mod(a,b)

array([[0, 0, 0],
       [1, 2, 3]])

In [16]:
a

array([1, 2, 3])

In [18]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.power(a,b)

array([[  1,   4,  27],
       [  1,  32, 729]])

In [20]:
np.less(a,b)

array([[False, False, False],
       [ True,  True,  True]])

In [ ]:
Examples
--------
>>> from numpy.linalg import inv
>>> a = np.array([[1., 2.], [3., 4.]])
>>> ainv = inv(a)
>>> np.allclose(np.dot(a, ainv), np.eye(2))
True
>>> np.allclose(np.dot(ainv, a), np.eye(2))
True

If a is a matrix object, then the return value is a matrix as well:

>>> ainv = inv(np.matrix(a))
>>> ainv
matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])


In [36]:
 from numpy.linalg import inv

In [39]:
 a = np.array([[1., 2.], [3., 4.]])
>>> ainv = inv(a)

In [40]:
 ainv  #inverse matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# power and log

In [88]:
np.square(e)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  4.],
       [ 9., 16.],
       [25., 36.]])

In [89]:
np.square(25)

625

In [90]:
np.sqrt(45)

6.708203932499369

In [91]:
np.sqrt(25)

5.0

In [92]:
np.cbrt(45)

3.556893304490063

In [93]:
np.cbrt(8)

2.0

In [94]:
np.log(5)

1.6094379124341003

In [95]:
np.log10(25)

1.3979400086720377

In [101]:
np.power(a,b)

array([[  1,   4,  27],
       [  1,  32, 729]])

In [102]:
np.ceil(2.3) #it give last value

3.0

In [103]:
np.floor(2.9) #it give exact value

2.0

In [104]:
np.round(2.9) #it give complite value

3.0

In [105]:
np.sin(45)

0.8509035245341184

In [106]:
np.cos(55)

0.022126756261955736

In [107]:
np.tan(95)

0.9357524720632393

# AGGRIGATION FUNCTION

In [108]:
e.mean()

2.25

In [109]:
e.max()

6.0

In [110]:
np.median(e)

1.0

In [123]:
g=[55,47,65,77,15,15,55]  #odd

In [126]:
np.median(g)#list or matrix no dout get right answer

55.0

In [132]:
sorted(g)

[15, 15, 47, 55, 55, 65, 77]

In [21]:
c=[13,15,17,19,21,25]


In [129]:
np.median(c)

18.0

In [130]:
sorted(c)

[13, 15, 17, 19, 21, 25]

In [22]:
np.argmax(c)   #it give index of max value

5

In [23]:
np.argmin(c)  #it give index of min value

0

In [139]:
e

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [3., 4.],
       [5., 6.]])

In [140]:
e.argmax(axis=0) #it give index of max value from row

array([5, 5], dtype=int64)

In [141]:
e.argmax(axis=1) #it give index of max value from row

array([0, 0, 0, 1, 1, 1], dtype=int64)

In [138]:
g

[55, 47, 65, 77, 15, 15, 55]

In [137]:
np.cumsum(g) #commulative sum

array([ 55, 102, 167, 244, 259, 274, 329])

In [24]:
d=np.array([1,3,5,7,9])

In [25]:
d.cumsum()

array([ 1,  4,  9, 16, 25])

# TRANSFORMING ARRAY

In [142]:
e.copy()

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [3., 4.],
       [5., 6.]])

In [147]:
np.unique(g)

array([15, 47, 55, 65, 77])

In [148]:
np.sort(g)

array([15, 15, 47, 55, 55, 65, 77])

In [151]:
g

[55, 47, 65, 77, 15, 15, 55]

In [149]:
np.argsort(g)

array([4, 5, 1, 0, 6, 2, 3], dtype=int64)

In [150]:
sorted(g)

[15, 15, 47, 55, 55, 65, 77]

In [154]:
d=[1,2,5,3]

In [155]:
np.argsort(d)

array([0, 1, 3, 2], dtype=int64)

In [157]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
np.ravel(b) #one by one

array([1, 2, 3, 4, 5, 6])

In [158]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

# CONCATENAT ARRAYS

In [26]:
x=np.array([1,2,3,4,5,6])

In [162]:
y=np.array([5,4,6,7,8,5])

In [163]:
x.ndim

1

In [164]:
y.ndim

1

In [167]:
np.vstack((x,y)) #add x and y vertically

array([[1, 2, 3, 4, 5, 6],
       [5, 4, 6, 7, 8, 5]])

In [168]:
np.hstack((x,y)) #add x and y horizontally

array([1, 2, 3, 4, 5, 6, 5, 4, 6, 7, 8, 5])

In [169]:
np.append(x,55)  #append anything in any arry

array([ 1,  2,  3,  4,  5,  6, 55])

In [170]:
np.append(x,[12,54,565])# we can append multiple values also only appennd do work of extend also

array([  1,   2,   3,   4,   5,   6,  12,  54, 565])

In [7]:
df = pd.DataFrame({'Salary':salary, 'Openings':openings})

NameError: name 'salary' is not defined

In [6]:
import pandas as pd

In [8]:
df = pd.DataFrame(salary, openings)

NameError: name 'salary' is not defined

In [9]:
df = pd.dataframe({'Salary':salary, 'Openings':openings})


AttributeError: module 'pandas' has no attribute 'dataframe'

In [10]:
df = DataFrame({'Salary':salary}, {'Openings':openings})


NameError: name 'DataFrame' is not defined

In [11]:
df = pd.DataFrame({'Salary':salary, 'Openings':openings})

NameError: name 'salary' is not defined